import React from 'react';
import Head from 'next/head';
import Tareas from './tareas';

export default function Home() {
  return (
    <>
      <Head>
        <title>Lista de Tareas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tareas />
    </>
  );
}
